### ISSUE TITLE
Cannot find packages

### ISSUE THREAD

**Issue by saintmalik** [johnssimon007/BrokenLinkHijacking#1]
I ran it using `go run main.go https://site.com`

and i got this error

![Screenshot 2021-08-22 at 6 10 42 PM](https://user-images.githubusercontent.com/37118134/130363965-0f24d92e-8d5e-494f-9252-d4c71a39b5fa.jpg)

**Comment by saintmalik** [comment]
I was able to fix it by installing those packages using this

`go get github.com/common-nighthawk/go-figure`
`go get github.com/jackdanger/collectlinks`

Thanks for this

**Comment by abhiabhi2306** [comment]
Hey @saintmalik 

You are missing the packages required locally, to get them you can use

`go get ./...
go build
go run main.go https://site.com
`
Regards,
Abhishek

**Comment by saintmalik** [comment]
Thanks 😊
